OntimizeWeb/ontimize-web-ngx

ontimize/components/form/o-form.component.ts

Using 'columns' attribute from o-form in order to query attributes which are not resitered through a component in the form.

o-form: add not registered attributes to getAttributesToQuery

---

ontimize/components/table/column/cell-editor/boolean/o-table-cell-editor-boolean.component.ts

Makes more visible the input types and returned types for each case,
adds protection against undefined on switch,
adds protection against number typed as string,
solves #154 making the internal value to be a number

#154 Splits comparison between types

---

CHANGELOG.md
ontimize/components/table/extensions/dialog/export/o-table-export-dialog.component.html
ontimize/components/table/extensions/dialog/export/o-table-export-dialog.component.ts
ontimize/components/table/extensions/header/table-menu/o-table-menu.component.ts
ontimize/components/table/o-table.component.ts

Visible buttons in export dialog, separated by ';'.
Default/not configured: show all.
Empty value (`visible-export-dialog-buttons=""`): hide all.
Closes #316

New `o-table` attribute `visible-export-dialog-buttons`

---

projects/ontimize-web-ngx/src/lib/services/navigation.service.ts

Fixed the loading not removed in form-layout-tabgroup when there is a insertion tab when return in navigation

Fixed the loading not removed in form-layout-tabgroup 

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts

The parent keys value was only added from _queryData()_ method. Now this piece of code is included in method _getComponentFilter()_, in that way when you call this method you retrieve all available filter values of the component.

[Bugfix/8.x.x ] Including parent keys value when exporting data

---

CHANGELOG.md
ontimize/components/o-service-base-component.class.ts

The parent keys value was only added from _queryData()_ method. Now this piece of code is included in method _getComponentFilter()_, in that way when you call this method you retrieve all available filter values of the component.

[Bugfix/4.x.x] Including parent keys value when exporting data

---

ontimize/components/input/checkbox/o-checkbox.component.ts
ontimize/components/input/slide-toggle/o-slide-toggle.component.ts

Fix overwrite sqltype in initialize method in o-checkbox component and o-slide-toggle

[4.x.x] Fix overwrite sqltype in initialize method

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts

- Deprecated old methods for the form toolbar actions
- Created new methods for the form toolbar actions with improved naming
- Added warnings in old methods for preventing users use them

Form toolbar action methods

---

projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-columns-filter/o-table-columns-filter.component.ts
projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.html
projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
projects/ontimize-web-ngx/src/lib/interfaces/o-table-menu.interface.ts

- New onVisibleFilterOptionChange event
- Don't refresh the o-table-menu with the reinitialize method of the table

[8.x.x] Fixed bug in filter column with reinitialize

---

projects/ontimize-web-ngx/src/lib/components/table/column/o-column.class.ts
projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-column-resizer/o-table-column-resizer.component.ts
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.scss
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts

- Fixed the bug when a table column has width configured
- Column width value is not recalculate when windows are resized (the default value will be auto) and the column autoadjust on the table
- Columns Width  in the  table is refreshing when horizontal-scroll input is changed

[8.x.x] Fixed bug in  width columns table

---

ontimize/components/table/extensions/header/table-column-resizer/o-table-column-resizer.component.ts
ontimize/components/table/o-table.component.html
ontimize/components/table/o-table.component.scss
ontimize/components/table/o-table.component.ts

1. Fixed the bug when a table column has width configured
2. Column width value is not recalculate when windows are resized (the default value will be auto) and the column autoadjust on the table
3. Columns width in the table is refreshing when horizontal-scroll input is changed

[4.x.x] Fixed bug in width columns table

---

ontimize/components/table/o-table.component.html

Fixed bug in expandable column with row-height='small' since if height = small, the height of the row was 40px

[4.x.x] Fixed bug in expandable column with row-height='small'

---

projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header-column-filter-icon/o-table-header-column-filter-icon.component.scss
projects/ontimize-web-ngx/src/lib/components/table/extensions/sort/sort-header.scss
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.scss
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
projects/ontimize-web-ngx/src/lib/components/table/styles/o-table-theme.scss

1. Fixed the position of the numbered indicator from filtering with differents row-height values
2. Fixed text overlapping with filter button in last column
3. Fixed that the min-width value is set by default 80px if it does not have value

[8.x.x] Indicator numbered position

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html

Fixed reference **rowIndex** because when using the multiTemplateDataRows directive to support multiple rows for each data object, the context of *matRowDef is the same except that the index value is replaced by dataIndex and renderIndex.

[8.x.x] Issue 541

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/pipes/o-currency.pipe.ts
projects/ontimize-web-ngx/src/lib/pipes/o-integer.pipe.ts
projects/ontimize-web-ngx/src/lib/pipes/o-percentage.pipe.ts
projects/ontimize-web-ngx/src/lib/pipes/o-real.pipe.ts
projects/ontimize-web-ngx/src/lib/services/number.service.ts

- Set pipes as impure
- Added useGrouping in the options  of Intl.NumberFormat
- Closes #566

[8.x.x] Issue 566

---

ontimize/components/input/combo/combo-renderer/o-combo-renderer.class.ts
ontimize/components/input/listpicker/listpicker-renderer/o-listpicker-renderer.class.ts
ontimize/components/table/config/o-table-gesture-config.ts
ontimize/components/table/o-table.component.ts

Scrolling on a touch device doesn't work if the target of the gesture is an element using the matTooltip directive
closes #576

[4.x.x] The table that will not allow scrolling when the user's touch it in tablet mode

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts

[8.x.x] O-table-row-expandable: error when exporting table data

---

ontimize/components/table/extensions/header/table-menu/o-table-menu.component.ts

The expandable column is added to the array of columns that are not taken into account in the export.

[4.x.x] Error to export table with expandable row

---

CHANGELOG.md
package.json
projects/ontimize-web-ngx/package.json
projects/ontimize-web-ngx/src/lib/components/app-header/o-app-header.component.ts
projects/ontimize-web-ngx/src/lib/components/app-sidenav/menu-item/o-app-sidenav-menu-item.component.ts
projects/ontimize-web-ngx/src/lib/components/user-info/o-user-info.component.ts
projects/ontimize-web-ngx/src/lib/config/o-providers.ts
projects/ontimize-web-ngx/src/lib/interfaces/auth-service.interface.ts
projects/ontimize-web-ngx/src/lib/interfaces/index.ts
projects/ontimize-web-ngx/src/lib/interfaces/login-service.interface.ts
projects/ontimize-web-ngx/src/lib/services/auth-guard.service.ts
projects/ontimize-web-ngx/src/lib/services/auth.service.ts
projects/ontimize-web-ngx/src/lib/services/base-service.class.ts
projects/ontimize-web-ngx/src/lib/services/factories.ts
projects/ontimize-web-ngx/src/lib/services/index.ts
projects/ontimize-web-ngx/src/lib/services/local-storage.service.ts
projects/ontimize-web-ngx/src/lib/services/login-storage.service.ts
projects/ontimize-web-ngx/src/lib/services/o-auth.service.ts
projects/ontimize-web-ngx/src/lib/services/ontimize/ontimize-base-service.class.ts
projects/ontimize-web-ngx/src/lib/services/ontimize/ontimize-ee.service.ts
projects/ontimize-web-ngx/src/lib/services/ontimize/ontimize-export.service.ts
projects/ontimize-web-ngx/src/lib/services/ontimize/ontimize-file.service.ts
projects/ontimize-web-ngx/src/lib/services/ontimize/ontimize.service.ts
projects/ontimize-web-ngx/src/lib/services/permissions/ontimize-ee-permissions.service.ts
projects/ontimize-web-ngx/src/lib/services/permissions/ontimize-permissions.service.ts
projects/ontimize-web-ngx/src/lib/services/remote-config.service.ts
projects/ontimize-web-ngx/src/lib/util/service.utils.ts

- `LoginService` has been splitted into an abstract class `AuthService` and its implementation `OntimizeAuthService`
- Method `redirectLogin` has been removed. Method `logout` from `AuthService` should provide this functionality. `OntimizeAuthService` still have this method as it is the default ontimize authentication implementation.
- Defined new Injection Token `O_AUTH_SERVICE` for providint/overriding the desired `AuthService` implementation

Refactor authentication

---

projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts

Added comprobation to check if initial-configuration is setted and has values to avoid filter-case-sensitive error in console.

[8.x.x] Quickfilter filter-case-sensitive error in console

---

projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
projects/ontimize-web-ngx/src/lib/interfaces/o-table-datasource.interface.ts

The destroy method is defined to launch when the table component is destroyed instead of disconnet method

New method destroy in o-table-datasource

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
projects/ontimize-web-ngx/src/lib/components/table/extensions/o-table-strategy.service.ts
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.scss
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
projects/ontimize-web-ngx/src/lib/interfaces/o-table-datasource.interface.ts

- New input  `virtual-scroll`
- Set min-height=400px in o-table-container class
- Refresh datasource in the table when refresh cdkVirtualScrollViewport viewchild
- Remove destroy method in o-table-datasource.service.ts (Revert commit 52aff20)

[8.x.x] New input virtual-scroll

---

CHANGELOG.md

A warning note was added about the incompatibility between the virtual-scroll and the table tooltip

[8.x.x] CHANGELOG: Added incompatible funcionalities the tooltip with virtual scrolling

---

projects/ontimize-web-ngx/src/lib/components/input/radio/o-radio.module.ts

Fixed wrong import of OContextMenuModule in ORadioModule

[8.x.x] Wrong import of OContextMenuModule in ORadioModule

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
projects/ontimize-web-ngx/src/lib/services/state/o-table-component-state.service.ts

- Closes #714 
- Fixing bug that the selected records are not being saved in the local storage.

[8.x.x] o-table doesn't work with select-all-checkbox-visible="yes"

---

projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts

Fixes #752, #751
All of the events emitted in virtual scrolling will be run outside the Angular zone and it is necessary  to run the callback using NgZone.run.

[8.x.x] CDK virtual scroller runs outside the ngZone

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts
projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
projects/ontimize-web-ngx/src/lib/components/table/extensions/o-table-strategy.service.ts
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts

Fixes #756 
- It's necessary to trigger **viewport.checkViewportSize**() on tab change.
> Its a temporarily fixed, waiting for the official fix for  [#10117](https://github.com/angular/components/issues/10117)
- Replaced own renderedRangeStream in virtual scroll strategy to viewport.renderedRangeStream

[8.x.x] o-table: blank screen on virtual scroll with mat tab group 

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
projects/ontimize-web-ngx/src/lib/components/table/extensions/o-table-strategy.service.ts
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts

Fixes #760
Modify the strategy to return data range
ActiveVirtualScroll variable has removed

[8.x.x] o-table: virtual scrolling works abnormally sometimes 

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/table/extensions/contextmenu/o-table-context-menu.component.ts

[8.x.x] o-table-context-menu: it does not show the translated value of the title attribute

---

projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/export/o-table-export-dialog.component.scss

Fixes #770
Set height butron to initial value

[8.x.x]o-table: export screen is displayed incorrectly 

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.scss

Grouping title wrapper always is aligned to left
Fixes #740

[8.x.x] Row grouping: align aggregation title depending on column type

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.html
projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.ts
projects/ontimize-web-ngx/src/lib/types/table/o-table-filter-by-column-data.type.ts

Fixes #777.
Removed getRowValue method  and  the rowValue attribute added in TableFilterByColumnData because the second time modal is opened, table [i] may not exist

bug in o-table: filter by column when the column has a custom renderer

---

projects/ontimize-web-ngx/ontimize.scss
projects/ontimize-web-ngx/src/lib/components/input/date-input/o-date-input.component.scss
projects/ontimize-web-ngx/src/lib/components/input/date-input/o-date-input.component.ts

- Modified the css properties to the new width  of the **mat-icon-button** with 32px instead of 40px
- Updated .mat-calendar-next-button,  .mat-calendar-previous-button classes

[8.x.x] Fixed the arrows are not displayed correctly in modal

---

projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts

Fixed the loadingSortingSubject not refresh in the template  because change detection not working with virtual scrolling

[8.5.2] Fixed not refresh loadingSorting in the template sometimes

---

projects/ontimize-web-ngx/src/lib/components/image/o-image.component.html
projects/ontimize-web-ngx/src/lib/components/image/o-image.component.ts

Avoid calling `getSrcValue` on every change detection cycle in `o-image` component
fixes #801

`o-image` performance

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/list/o-list.component.ts

Deleted code where the value of query-rows stored in localStorage is checked because this value is not stored. Closes #847

[8.x.x] fixed working of query-rows in o-list component

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/form/cache/o-form.cache.class.ts
projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form-confirm-exit.service.ts
projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form.navigation.class.ts
projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts

Fixes #595 
1. The method **_subscribeToDiscardChanges_** allow to show confirm dialog if it is insert form
2. Updated **_isInitialStateChanged_** method, the ignore-exit attributes are removed on `currentKeys` array
3.  Resolved code smell by Sonar
Tested
> 1. Close tab, modal with form layout manager
> 2. Change URL
> 3. Call closeDetail method

[8.x.x] o-form: Close insert form without confirmation

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/filter-builder/o-filter-builder.component.ts
projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.ts
projects/ontimize-web-ngx/src/lib/components/input/real-input/o-real-input.component.ts
projects/ontimize-web-ngx/src/lib/util/codes.ts

1. Fixes #788 
2. Avoid emitting the valueChanges event in the setIsReadOnly method
3. New attribute `query-on-change-event-type `in `o-filter-builder` component

[8.x.x] o-filter-builder: launches as many queries as there are combos 

---

projects/ontimize-web-ngx/src/lib/components/input/input.scss
projects/ontimize-web-ngx/src/lib/components/input/password-input/o-password-input.component.html

- Updated classes when mat-icon is added as matPrefix or matSuffix
- Hide button when the component has set `read-only='yes'` and `enabled='yes'`

[8.x.x] o-password-input:  Bugs with show-password-button

---

projects/ontimize-web-ngx/ontimize.scss
projects/ontimize-web-ngx/src/lib/components/container/o-container-collapsible.component.scss
projects/ontimize-web-ngx/src/lib/components/input/date-input/o-date-input.component.scss
projects/ontimize-web-ngx/src/lib/components/input/date-input/o-date-input.component.ts

Fixes #949, moved css styles from o-date-input to ontimize.scss because it's common code.
Fixes css error

[8.x.x] o-table-cell-editor-date and o-table-cell-editor-time: the arrow icons dont show in date popup

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/table/index.ts
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
projects/ontimize-web-ngx/src/lib/components/table/utils/index.ts
projects/ontimize-web-ngx/src/lib/components/table/utils/o-table.tokens.ts
projects/ontimize-web-ngx/src/lib/types/table/index.ts
projects/ontimize-web-ngx/src/lib/types/table/o-table-global-config.type.ts

1. Set `auto-adjust= true` by default
2. New injectionToken O_TABLE_GLOBAL_CONFIG
3. Fixes #1045

[8.x.x] o-table: set `auto-adjust` input to true by default

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.html
projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.scss
projects/ontimize-web-ngx/src/lib/components/grid/o-grid.module.ts
projects/ontimize-web-ngx/src/lib/components/list/o-list-theme.scss
projects/ontimize-web-ngx/src/lib/components/list/o-list.component.html
projects/ontimize-web-ngx/src/lib/components/list/o-list.component.scss
projects/ontimize-web-ngx/src/lib/components/list/o-list.module.ts
projects/ontimize-web-ngx/src/lib/components/o-data-toolbar/o-data-toolbar.component.html
projects/ontimize-web-ngx/src/lib/components/o-data-toolbar/o-data-toolbar.component.scss
projects/ontimize-web-ngx/src/lib/components/o-data-toolbar/o-data-toolbar.component.ts
projects/ontimize-web-ngx/src/lib/components/o-data-toolbar/o-data-toolbar.module.ts
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.scss
projects/ontimize-web-ngx/src/lib/components/table/o-table.module.ts
projects/ontimize-web-ngx/src/lib/components/theming/app-global-theme.scss

- New component o-data-toolbar
-  New CSS class `o-table-toolbar`, `o-list-toolbar`, `o-grid-toolbar`
-  Unified the styles of the titles of the `o-table`, `o-list`, `o-grid` with new CSS class to `title` and therefore removed CSS class `table-title` and `o-list-title`

o-list, o-grid, o-table: Allow to add custom content in toolbar

---

projects/ontimize-web-ngx/src/lib/types/index.ts

Reverting the removal of the SQLOrder type export

Reverting the removal of the SQLOrder type export

---

projects/ontimize-web-ngx/src/lib/components/input/input.scss
projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
projects/ontimize-web-ngx/src/lib/services/state/o-table-component-state.service.ts

Fixed  
- not filtering when there is no OTableColumnsFilterComponet configured
- column filter values ​​being saved to localstorate
- scrolling being shown when filtering by column in custom mode with `appearance = padding`

o-table with pageable=no the filter by column does not work

---

CHANGELOG.md
package.json
projects/ontimize-web-ngx/package.json
projects/ontimize-web-ngx/src/lib/components/button-toggle/o-button-toggle.component.html

Fixed `o-button-toggle` labels inside `o-button-toggle-group` not being translated

[8.x.x] Translate o-button-toggle-group

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/components/filter-builder/o-filter-builder.component.ts

`oFilterBuilderClear` directive not clearing the value of the `o-combo` multiple 

---

CHANGELOG.md
projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts

Fixed not opening the detail tab if you had previously opened a new tab again

Form-layout-manager with mode='tab' sometimes does not open detail

---

projects/ontimize-web-ngx/src/lib/components/table/column/cell-renderer/service/o-table-cell-renderer-service.component.ts
projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-column-resizer/o-table-column-resizer.component.scss
projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header-column-filter-icon/o-table-header-column-filter-icon.component.scss
projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header/o-table-header.component.html
projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header/o-table-header.component.scss
projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header/o-table-header.component.ts
projects/ontimize-web-ngx/src/lib/components/table/extensions/sort/sort-header.scss
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.scss
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
projects/ontimize-web-ngx/src/lib/types/table/o-table-global-config.type.ts

- Set `auto-align-titles=true` by default in table headers
- New property `autoAlignTitles` in injection token `O_TABLE_GLOBAL_CONFIG`
- Removed containers with `position:absolute` in the table headers and the adapted styles 
- Fixed title header align and cell align by default in o-table-column are distinct

Set auto-align-titles=true by default

---

projects/ontimize-web-ngx/src/lib/components/input/integer-input/o-integer-input.component.ts

Fixes #1237 
Tested on Firefox 102.12 (version from 06/2022). According to Firefox usage share ~95% is using this or more recent versions

o-integer: removing unnecesary firefox workaround

---

projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts

1. Fixed that the input `content-align` was not taken into account when aligning the titles of the tables
2. Set default values ​​when getting property from `O_TABLE_GLOBAL_CONFIG` injection token

Fixed that the input `content-align` was not taken into account when aligning the titles of the tables

---

projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts
projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
projects/ontimize-web-ngx/src/lib/types/table/o-column-display.type.ts

- New methods  refreshColumnsWidthFromLocalStorage and refreshColumnsWidthFromOriginalDefinition
- Not refresh column widths when launch updateScrolledState listener
- Fixes #1240

Fixes the width columns resized by the user does not remain

---

projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.html

[8.x.x]o-table-quickfilter:Fixes menu open when ENTER in editable column

---

projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form.navigation.class.ts

Fixed confirmation message not being displayed on a form with mode='insert' without form-layout-manager

Displayed confirmation message on o-form in insert mode 
