OntimizeWeb/ontimize-web-ngx

.gitignore, CHANGELOG.md, ontimize/components/input/listpicker/o-list-picker-theme.scss, ontimize/components/input/listpicker/o-list-picker.component.scss, ontimize/components/input/listpicker/o-list-picker.component.ts, ontimize/components/list/o-list.component.ts, ontimize/components/table/cell-renderer/o-table-cell-renderer-boolean.component.ts, ontimize/components/table/o-table.component.ts, ontimize/components/theming/all-theme.scss, ontimize/config/o-providers.ts, ontimize/services/auth-guard.service.ts, ontimize/services/o-translate.service.ts, package.json
=> 2.0.0 rc.3

ontimize/components/input/date-input/o-date-input.component.ts, ontimize/components/input/hour-input/o-hour-input.component.ts, ontimize/components/o-form-data-component.class.ts, ontimize/components/table/extensions/header/table-menu/o-table-menu.component.ts
Added new function to o-hour-component getValue()
=> Fix Bug 300

ontimize/components/input/time-input/o-time-input.component.html, ontimize/components/input/time-input/o-time-input.component.ts
Fixes strange behabiour when there is more than one `o-time-input` in the same form
=> Make `o-time-input` internal attr's depend on component attr

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/language-selector/o-language-selector.component.ts, projects/ontimize-web-ngx/src/lib/config/o-providers.ts, projects/ontimize-web-ngx/src/lib/services/translate/o-translate.service.ts, projects/ontimize-web-ngx/src/lib/util/codes.ts
=> Language selector change

projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/export/o-table-export-dialog.component.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-export-configuration.class.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/interfaces/export-service.interface.ts, projects/ontimize-web-ngx/src/lib/interfaces/index.ts, projects/ontimize-web-ngx/src/lib/services/export-service.provider.ts, projects/ontimize-web-ngx/src/lib/services/ontimize-export.service.ts, projects/ontimize-web-ngx/src/lib/types/config.type.ts
=> Extend export service

projects/ontimize-web-ngx/src/lib/services/navigation.service.ts
Reverts OntimizeWeb/ontimize-web-ngx#358
=> Revert "Fixed the loading not removed in form-layout-tabgroup "

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/app-header/o-app-header.component.html, projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.html, projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.ts, projects/ontimize-web-ngx/src/lib/layouts/app-layout/o-app-layout.component.html, projects/ontimize-web-ngx/src/lib/layouts/app-layout/o-app-layout.component.ts, projects/ontimize-web-ngx/src/lib/util/codes.ts
=> (o-app-layout): the menu icon appears in sidenav when mode="desktop" and show-header="yes"

projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.scss
=>  scroll not worked when searchable="yes"

CHANGELOG.md, ontimize/components/table/extensions/pipes/o-table-row-class.pipe.ts, ontimize/components/table/o-table.component.html, ontimize/components/table/o-table.component.ts
It allows adding css classes to table rows depending on their cell values
Closes #367
=> o-table: new attribute `row-class`

projects/ontimize-web-ngx/src/lib/components/table/extensions/footer/expanded/o-table-expanded-footer.directive.ts
(cherry picked from commit 30e29912534f841a4a1a7364ebaed216bce2694d)
=> [8.x.x] Fixed not showing empty result message

ontimize/components/table/o-table-expanded-footer.directive.ts
not showing empty result message when controls="no"
=> [4.x.x] Fixed not showing empty result message

ontimize/components/table/extensions/header/table-menu/o-table-menu.component.ts, ontimize/components/table/o-table-expanded-footer.directive.ts, ontimize/components/table/o-table.component.ts
- Create new event onVisibleColumnsChange
- Updated colspan in td showing the message that there are no results
=> [Bugfix/4.x.x] not refresh width table columns

projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table-options.class.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Initialized oTableOptions variable in initialize method
=> [8.x.x] - Fixed bug reinitializing columns

projects/ontimize-web-ngx/src/lib/components/input/date-input/o-date-input.component.ts, projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-input.component.html, projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-input.component.ts, projects/ontimize-web-ngx/src/lib/util/util.ts
The new value types for o-daterange-input are: string | date | timestamp | iso-8601
The function is created on Utils file. This funtion converts data to the object required in daterange input.
=> Feature/8.x.x Added New ValueTypes to Daterange Component

projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts
(cherry picked from commit 10048abc0779b6d6d2cafff1f8db9a50f1bc8e7c)
=> [8.x.x] Fixed not recovering query rows from localstorage

ontimize/components/o-service-base-component.class.ts
=> [4.x.x] Fixed not recovering query rows from localstorage

ontimize/components/grid/o-grid.component.ts
(cherry picked from commit 337ebb7959a7c254ae400e15287d65469067d429)
=>  [4.x.x] Fixed reloadData method in grid

projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.ts
Fixed reloadData method when pageable=no have to call queryData method as the list and table component
=> [8.x.x] Fixed reloadData method in grid

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/config/o-providers.ts, projects/ontimize-web-ngx/src/lib/services/translate/o-translate.service.ts, projects/ontimize-web-ngx/src/lib/types/config.type.ts
Added new param to app.config defaultLocale
=> [8.x.x] Default Locale added and working

ontimize/components/image/o-image.component.html, ontimize/components/image/o-image.component.scss, ontimize/components/image/o-image.component.ts
=> [4.x.x] Fixing bug in o-image

projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Fixed the message that no results were found when there was data.
=> Fixed the message that no results were found when there was data.

projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts
Initialized layoutAling= 'start stretch' instead of 'start start
=> [8.x.x] Initialized layoutAling= 'start stretch' 

projects/ontimize-web-ngx/src/lib/components/input/checkbox/o-checkbox.component.ts, projects/ontimize-web-ngx/src/lib/components/input/slide-toggle/o-slide-toggle.component.ts
Fix overwrite sqltype in initialize method in o-checkbox component and o-slide-toggle
=> [8.x.x] Fix overwrite sqltype in initialize method

projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker-dialog.component.ts
Removed expression changed after it has been checked error in o-list-picker
cherry picked from commit fd92f90a8f5774115adcd96d29691acc06390a9d)
=> [8.x.x] Removed ExpressionChangedAfterItHasBeenCheckedError error in o-list-picker

ontimize/components/input/listpicker/o-list-picker-dialog.component.ts
Removed expression changed after it has been checked error in o-list-picker
=> [4.x.x] Removed expression changed after it has been checked error in o-list-picker

ontimize/components/table/o-table.component.ts
Fixed error "ViewDestroyedError: Attempt to use a destroyed view: detectChanges" that was displayed by console
=> [4.x.x]  Error ViewDestroyedError

projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/types/o-table-initialization-options.type.ts
Added new option 'filterColumns' in reinitialize method
=> [8.x.x] Added new option 'filterColumns' in reinitialize method

ontimize/components/table/o-table.component.ts
(cherry picked from commit 361b8c18eb1c081e18c10f39bc9b5f28f8bebdf2)
=> [4.x.x] Added new option 'filterColumns' in reinitialize method

CHANGELOG.md, ontimize/components/table/extensions/header/table-menu/o-table-menu.component.ts, ontimize/components/table/extensions/o-table-storage.class.ts, ontimize/components/table/o-table-theme.scss, ontimize/components/table/o-table.component.html, ontimize/components/table/o-table.component.ts
- Fixing reloadData when clear column filters
- New filter-column-active-by-default attribute
- Changed column filter icon
=> [4.x.x] New `filter-column-active-by-default` attribute

ontimize/components/table/extensions/header/table-columns-filter/o-table-columns-filter.component.ts, ontimize/components/table/extensions/header/table-menu/o-table-menu.component.html, ontimize/components/table/extensions/header/table-menu/o-table-menu.component.ts, ontimize/components/table/o-table.component.ts
(cherry picked from commit 6dda28d7c60497ed75ec06c9abb5f5ac1fe65387)
=> [4.x.x] Fixed bug in filter column with reinitialize

CHANGELOG.md, ontimize/components/button/o-button.component.html, ontimize/components/button/o-button.component.ts
Added the new `enabled` attribute
=> [4.x.x] new `enabled` attribute

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/button/o-button.component.html, projects/ontimize-web-ngx/src/lib/components/button/o-button.component.ts
Added the new `enabled` attribute
=> [8.x.x] new `enabled` attribute

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/button/o-button.component.html, projects/ontimize-web-ngx/src/lib/components/button/o-button.component.ts
=> [8.x.x] new `color` attribute in o-button

CHANGELOG.md, ontimize/components/button/o-button.component.html, ontimize/components/button/o-button.component.ts
=> [4.x.x] new `color` attribute in o-button

projects/ontimize-web-ngx/src/lib/components/table/column/o-column.class.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.scss, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
1. Fixed expandable column Width inside tabs
2. Not refresh column width when hiding / showing columns
=> [8.x.x] Fixed expandable column width

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.scss, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
1. New `auto-adjust` attribute
2. Updated CHANGELOG.md
=> [8.x.x]  New `auto-adjust` attribute

projects/ontimize-web-ngx/src/lib/components/container/o-container-theme.scss
Hide border in o-container-title in collapsible row/column when child of o-row/o-column
=> [8.x.x] Hide border in o-container-title in collapsible row

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/o-table-header-components.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header-column-filter-icon/o-table-header-column-filter-icon.component.html, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header-column-filter-icon/o-table-header-column-filter-icon.component.scss, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header-column-filter-icon/o-table-header-column-filter-icon.component.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/sort/o-mat-sort-header.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/sort/sort-header.scss, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.scss, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/components/table/styles/o-table-theme.scss
- New `o-table-header-column-filter-icon` component
- Added o-table-header-indicator-numbered class in o-mat-sort component
=> [8.x.x] Filter indicator numbered

projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
(cherry picked from commit ff176a7c4baedb0c713e36919b1dc9978bc9ba6c)
=> [8.x.x] Fixed bug in expandable row with height='small'

projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/apply-configuration/o-table-apply-configuration-dialog.component.html, projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.html, projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/load-filter/o-table-load-filter-dialog.component.html, projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/store-filter/o-table-store-filter-dialog.component.html, projects/ontimize-web-ngx/src/lib/components/table/styles/o-table-theme.scss, projects/ontimize-web-ngx/src/lib/shared/components/dialog/o-dialog.component.html
- Removed class="mat-primary" in buttons dialogs
- Updated the .selected class in table in dark mode
=> [8.x.x] Does not display button text in dialogs in dark mode

ontimize/components/dialog/o-dialog.component.html, ontimize/components/table/extensions/dialog/apply-configuration/o-table-apply-configuration-dialog.component.html, ontimize/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.html, ontimize/components/table/extensions/dialog/load-filter/o-table-load-filter-dialog.component.html, ontimize/components/table/extensions/dialog/store-filter/o-table-store-filter-dialog.component.html
(cherry picked from commit 60c1e2247a22ecf0443d5f79560d2777da0ef2b6)
=> [4.x.x]Removed class="mat-primary" in buttons dialogs

CHANGELOG.md, package.json, projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.html
Setting correct value in `mat-dialog-close` variable
=> [8.x.x] Not filter by column

CHANGELOG.md, package.json, projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.html
Reverts OntimizeWeb/ontimize-web-ngx#474
=> Revert "[8.x.x] Not filter by column"

CHANGELOG.md, projects/ontimize-web-ngx/package.json
=> Merged 8.x.x into master

projects/ontimize-web-ngx/src/lib/components/container/o-container-component.class.ts
Fixed line above title in container component
=> [8.x.x] Line above title in container component

ontimize/components/container/column/o-column.component.html, ontimize/components/container/o-container-component.class.ts, ontimize/components/container/row/o-row.component.html
This PR is to solve the next issue:
- attr _appearence="outline"_ is not working without adding the attribute _title_.
=> [4.x.x] Appearence outline without title in o-column component

projects/ontimize-web-ngx/src/lib/components/container/column/o-column.component.html, projects/ontimize-web-ngx/src/lib/components/container/row/o-row.component.html
This PR is to solve the next issue:
- attr _appearence="outline"_ is not working without adding the attribute _title_.
=> [8.x.x] Appearence outline without title in o-column component 

ontimize/components/app-sidenav/image/o-app-sidenav-image.component.ts
=> Update sidenav image when component attributes change

CHANGELOG.md, ontimize/components/grid/o-grid.component.html, ontimize/components/grid/o-grid.component.scss, ontimize/components/grid/o-grid.component.ts
- New button
- New insert-button-position and insert-button-floatable inputs
=> [4.x.x] New button grid

CHANGELOG.md, ontimize/components/input/listpicker/o-list-picker-dialog.component.ts
- Closes #503
- Fixed that scrolling concatenates the data without filtering
=> [4.x.x] Replicated last value in scroll list picker

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker-dialog.component.html, projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker-dialog.component.scss, projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker-dialog.component.ts, projects/ontimize-web-ngx/src/lib/shared/material/custom.material.module.ts
Added virtual scrolling in o-list-picker
=> [8.x.x]Replicated last value in scroll list picker

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-input.component.html, projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-input.component.ts, projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-input.directive.ts, projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-picker.component.html, projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-picker.component.ts, projects/ontimize-web-ngx/src/lib/util/codes.ts
- New 'mode' input in o-date-range
- Improved ranges selection
=> [8.x.x] New attribute `mode` in data range component

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.html, projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-columns-filter/columns/o-table-columns-filter-column.component.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-columns-filter/o-table-columns-filter.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
New start-view input in OTableColumnsFilterColumnComponent for intial view in datepicker. 
- [month|year|multi-year] Default: month
=> [8.x.x] New start-view input in OTableColumnsFilterColumnComponent

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.html, projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.ts
Fixed in multiple combo
- SetValue doesnt work
- SetSelectedItems doesnt work
- If data is null and you put multiple-trigger-label = true the component  doesnt work
=> [8.x.x] Improvements combo

ontimize/components/table/o-table.component.ts
(cherry picked from commit 09e58474a858f8364236b5a332647bb429c1a28a)
=> [4.x.x]Fixed content duplicating

projects/ontimize-web-ngx/src/lib/components/table/extensions/contextmenu/o-table-context-menu.component.html, projects/ontimize-web-ngx/src/lib/components/table/extensions/contextmenu/o-table-context-menu.component.ts
Fixed the filter by column icon not being activated when filtering by value with the context menu
=> [8.x.x] Fixed the filter by column icon not being activated

CHANGELOG.md, ontimize/components/list/o-list.component.ts
=> [4.x.x] Parse `sort-columns` in `o-list` when value is set

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.ts
=> [8.x.x] Parse `sort-columns` in `o-list` when value is set

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/validators/o-validators.ts
=> [8.x.x] New pattern validator

CHANGELOG.md, ontimize/components/table/extensions/row/table-row-expandable/o-table-row-expandable.component.ts, ontimize/components/table/o-table.component.ts
- New `multiple` input in o-table-row-expandable
Closes #545
=> [4.x.x] New `multiple` input in o-table-row-expandable

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/extensions/row/table-row-expandable/o-table-row-expandable.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
- New `multiple` input in o-table-row-expandable
Closes #545
=> [8.x.x] New `multiple` input in o-table-row-expandable

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/form/o-form.component.html, projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts, projects/ontimize-web-ngx/src/lib/components/form/toolbar/o-form-toolbar.component.ts
=> [8.x.x] New event `onCancel` in `o-form` component

projects/ontimize-web-ngx/src/lib/components/input/integer-input/o-integer-input.component.ts, projects/ontimize-web-ngx/src/lib/components/input/real-input/o-real-input.component.ts, projects/ontimize-web-ngx/src/lib/services/number.service.ts
- Ignore min decimal digits validator in real input
- Avoid rounding parsing real values
=> [8.x.x] Parse real values in `o-real-input`

projects/ontimize-web-ngx/src/lib/services/translate/o-translate-http-loader.ts
=> Do not parse remote bundle error object as translations

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/date/o-table-cell-editor-date.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/integer/o-table-cell-editor-integer.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/o-base-table-cell-editor.class.ts, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/real/o-table-cell-editor-real.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/text/o-table-cell-editor-text.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/time/o-table-cell-editor-time.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/time/o-table-cell-editor-time.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
- Fixed not set new value in table-cell-editor-time
- Fixed not show popups of the table cell editors as the time or date picker
=> [8.x.x]Not set new value in table cell editor time

projects/ontimize-web-ngx/src/lib/layouts/card-menu-layout/o-card-menu-layout.component.scss
Fix card menu item in small resolutions.
=> [8.x.x] Fix height in card menu items

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/config/o-table-gesture-config.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.module.ts
Fixed mat-tooltip prevent touch scrolling in table
=> [8.x.x] The table that will not allow scrolling when the user's touch it in tablet mode

CHANGELOG.md, ontimize/components/table/config/o-table-gesture-config.ts
Fixed  prevent touch vertical and horizontal scrolling in table
=> [4.x.x] Fixed  prevent touch vertical and horizontal scrolling in table

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker.component.ts, projects/ontimize-web-ngx/src/lib/components/o-form-data-component.class.ts, projects/ontimize-web-ngx/src/lib/directives/locker.directive.ts
=> [8.2.5] oLocker checks component permissions

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/combo/combo-renderer/boolean/o-combo-renderer-boolean.component.html, projects/ontimize-web-ngx/src/lib/components/input/combo/combo-renderer/boolean/o-combo-renderer-boolean.component.ts, projects/ontimize-web-ngx/src/lib/components/input/combo/combo-renderer/o-combo-renderer.class.ts, projects/ontimize-web-ngx/src/lib/components/input/o-form-service-component.class.ts
=> [8.2.5] Fixing o-combo custom renderers

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker.component.ts
=> [8.2.5] o-list-picker displays required error with valid initial data 

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/listpicker/listpicker-renderer/o-list-picker-renderer.class.ts, projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker-dialog.component.html, projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker-dialog.component.ts, projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker.component.html, projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker.component.ts
=> [8.2.5] Fixing o-list-picker custom renderers

projects/ontimize-web-ngx/src/lib/components/table/extensions/footer/paginator/o-base-table-paginator.class.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/footer/paginator/o-table-paginator.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/interfaces/o-table-paginator.interface.ts
Initialize paginator attributes with table attributes when they are available
Fixes #631
=> o-table query images for all rows shown

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts, projects/ontimize-web-ngx/src/lib/components/table/column/cell-renderer/o-base-table-cell-renderer.class.ts, projects/ontimize-web-ngx/src/lib/components/table/column/cell-renderer/service/o-table-cell-renderer-service.component.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
=> Aborting query when filtering service renderer columns with no results

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.html, projects/ontimize-web-ngx/src/lib/components/input/search-input/o-search-input.component.ts, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.html, projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.html, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
=> New quick-filter-placeholder imput

projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.ts, projects/ontimize-web-ngx/src/lib/services/state/o-grid-component-state.class.ts, projects/ontimize-web-ngx/src/lib/services/state/o-grid-component-state.service.ts
=> o-grid quickfilter data storage

projects/ontimize-web-ngx/src/lib/components/table/extensions/footer/expanded/o-table-expanded-footer.directive.ts, projects/ontimize-web-ngx/src/lib/interfaces/o-table-quickfilter.interface.ts
=> Update tabla 'no data' message automatically with quick filter value

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.html, projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.ts, projects/ontimize-web-ngx/src/lib/components/input/search-input/o-search-input.component.ts, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.ts, projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts, projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/sort/o-mat-sort.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/services/state/o-grid-component-state.service.ts, projects/ontimize-web-ngx/src/lib/services/state/o-list-component-state.service.ts
Closes Issue #639 and Issue #643
=> Fixing o-grid and o-list bugs and rendering problems

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/input-theme.scss, projects/ontimize-web-ngx/src/lib/components/input/search-input/o-search-input.component.html, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.html, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.scss
=> [8.x.x] Icon color to placeholder in quickfilter and fix icon position

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/types/table/o-table-initialization-options.type.ts
=> [8.x.x] New input for o-table visible-columns-by-default

projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/dialog/o-form-layout-dialog.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/split-pane/o-form-layout-split-pane.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts, projects/ontimize-web-ngx/src/lib/services/state/index.ts, projects/ontimize-web-ngx/src/lib/services/state/o-table-component-state.service.ts
=> Fixing errors in o-form-layout-manager storage

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/visible-columns/o-table-visible-columns-dialog.component.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/i18n/i18n.ts, projects/ontimize-web-ngx/src/lib/interfaces/o-table-datasource.interface.ts
=> Show a warning message when a table column with active filters/sorting visibility changes

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/footer/expanded/o-table-expanded-footer.directive.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/util/service.utils.ts
=> ServiceBaseComponent: Retrieve parent keys values from url when form is not present

.github/workflows/build-ci.yml
It is added `build-ci.yml` workflow that is going to build the framework each time a Pull Request is merged into branches: 8.x.x or 4.x.x
=> Adding build CI workflows

.github/workflows/build-manually.yml
New workflow for launching code build manually from a specific branch.
=> Adding build manually workflow

projects/ontimize-web-ngx/src/lib/components/contextmenu/o-context-menu.component.ts, projects/ontimize-web-ngx/src/lib/components/contextmenu/o-context-menu.directive.ts, projects/ontimize-web-ngx/src/lib/components/contextmenu/o-context-menu.service.ts
=> Injecting o-context-menu.service in each o-context-menu

projects/ontimize-web-ngx/src/lib/components/table/extensions/footer/expanded/o-table-expanded-footer.directive.ts
=> [8.x.x] Error in OTableExpandedFooterDirective: Cannot read property 'onChange' of undefined

projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts, projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
Closes #680 (only a couple of cases)
=> Fixing small bugs in updateStorageState

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Easy solution commented in https://github.com/angular/angular/issues/14748#issuecomment-312148877
=> [8.x.x]  O-table-quickfilter component logs ExpressionChangedAfterItHasBeenCheckedError

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.ts, projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker.component.ts, projects/ontimize-web-ngx/src/lib/components/input/o-form-service-component.class.ts
- Remove commented code
- Remove the verification code if the value does not exist in the data array in the setValue method in the o-combo component. This check is done in syncDataIndex and is common to o-combo and o-list-picker. Also, added a per console warning
=> [8.x.x] Function setFieldValues not working fine on o-combo and o-list-picker

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/date-input/o-date-input.component.ts, projects/ontimize-web-ngx/src/lib/components/input/time-input/o-time-input.component.ts, projects/ontimize-web-ngx/src/lib/util/util.ts
=> New o-time-input value-type and value-format inputs

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/form/cache/o-form.cache.class.ts, projects/ontimize-web-ngx/src/lib/components/form/guards/o-form-can-deactivate.guard.ts, projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form-confirm-exit.service.ts, projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form.navigation.class.ts, projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts
=> New attribute `ignore-on-exit` in `o-form` component

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.html, projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.module.ts, projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker.component.html, projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker.module.ts, projects/ontimize-web-ngx/src/lib/components/input/o-form-service-component.class.ts, projects/ontimize-web-ngx/src/lib/components/input/radio/o-radio.component.html, projects/ontimize-web-ngx/src/lib/components/input/radio/o-radio.module.ts, projects/ontimize-web-ngx/src/lib/i18n/i18n.ts
=> New o-context-menu for reload components data

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.html, projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header-column-filter-icon/o-table-header-column-filter-icon.component.ts, projects/ontimize-web-ngx/src/lib/types/table/o-column-value-filter.type.ts
=> [8.x.x] Updating column filter to show all the available values

projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts
=> Form layout tabgroup set modified state in active tab

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.ts
=> [8.x.x] Remove columns with searchable tag to false from query

projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.html, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.html
=> [8.x.x] o-grid and o-list quickfilter placeholder is no longer floating

projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts
=> Hide form layout spinner when creating tabs from app state

projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form.navigation.class.ts, projects/ontimize-web-ngx/src/lib/services/navigation.service.ts
=> Protect navigation when history is empty

projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts
=> Check default insert route when navigation data is empty

projects/ontimize-web-ngx/src/lib/components/form/guards/o-form-can-deactivate.guard.ts, projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form-confirm-exit.service.ts
=> [8.x.x] Fixing discard changes dialog error

projects/ontimize-web-ngx/src/lib/components/contextmenu/o-context-menu-overlay.service.ts, projects/ontimize-web-ngx/src/lib/components/contextmenu/o-context-menu.service.ts
=> [8.x.x] Common overlay references for context menus

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/row/o-table-row-group.class.ts
Updated sum, count, avg, max and min operations when data is grouped
=> [8.x.x] Row grouping: collapsing row groups makes columns aggregate have a wrong value

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/form/cache/o-form.cache.class.ts, projects/ontimize-web-ngx/src/lib/components/form/guards/o-form-can-deactivate.guard.ts, projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form.navigation.class.ts, projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts, projects/ontimize-web-ngx/src/lib/components/form/toolbar/o-form-toolbar.component.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/footer/expanded/o-table-expanded-footer.directive.ts, projects/ontimize-web-ngx/src/lib/interfaces/o-form-layout-manager-mode.interface.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/dialog/o-form-layout-dialog.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/guards/o-form-layout-can-activate-child.guard.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/split-pane/o-form-layout-split-pane.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.html, projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts, projects/ontimize-web-ngx/src/lib/types/form-layout-detail-component-data.type.ts, projects/ontimize-web-ngx/src/lib/util/util.ts
=> o-form-layout-manager updating active opened data to have separated inner forms information

projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
=> [8.x.x] Row grouping: add suffix to aggregate title depending on column type

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Alignment on aggregate column heading with same default column type alignment
=> [8.x.x] Row grouping: align aggregation title depending on column type

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts
=> [8.x.x] Fix layout manager on tab mode after refreshing page

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-columns-grouping/columns/o-table-columns-grouping-column.component.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/row/o-table-row-group.class.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
=> [8.x.x] Fixing bug in expand-groups-same-level and change-aggregate-same-level inputs

projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts
=> [8.x.x] Bug in o-form-layout-manager tab mode: new detail

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/bar-menu/menu-nested/o-bar-menu-nested.component.html, projects/ontimize-web-ngx/src/lib/components/bar-menu/menu-nested/o-bar-menu-nested.component.ts
=> Change applicatio locale from `o-bar-menu` with `app.menu.config`

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
=> [8.5.2] Bug when using aggregate column and checkbox on o-table

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/util/util.ts
=> [8.5.3] o-time-input: clicking on the button to clear the field shows today's date and time

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/list/list-item/o-list-item.component.html, projects/ontimize-web-ngx/src/lib/components/list/list-item/o-list-item.component.ts, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.ts, projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts
=> [8.5.4] Fixing bug in list selection model

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/password-input/o-password-input.component.html, projects/ontimize-web-ngx/src/lib/components/input/password-input/o-password-input.component.ts
=> [8.x.x] Added the option to o-password-inputs to show the plain text instead of dots

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/extensions/row/table-row-expandable/o-table-row-expandable.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
Closes #811 
New input added to o-table to make changes in expandable-row before load information.
expanded-callback: Function
=> [8.x.x] Expandable-callback input added to o-table

projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-picker.component.html, projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-picker.component.scss
Fixed Unexpected unknown unit bugs detected on `o-datarange-picker.component.scss`
Fixed duplicated declarations
=> [SONAR] Fix reported bugs by Sonar

.github/workflows/sonar.yml, .gitignore, sonar-project.properties
Configures GitHub action workflow for sending results to SonarCloud.io
=> Configure SonarCloud 

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
=> Fixed error of not maintained column order changes after the application is reloaded

projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.html
=> [8.5.6] Fix onBlur output no beeing fired

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/button/o-button.component.html, projects/ontimize-web-ngx/src/lib/components/button/o-button.component.scss, projects/ontimize-web-ngx/src/lib/components/button/o-button.component.ts
=> Fixed the problem that prevented disabling the button click when it was disabled

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form.navigation.class.ts, projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts, projects/ontimize-web-ngx/src/lib/interfaces/o-form-layout-manager-mode.interface.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/dialog/o-form-layout-dialog.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts
=> [8.5.6] Fixed the problem that shows a dialog after insert new data with o-form-layout-manager

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form.navigation.class.ts, projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts, projects/ontimize-web-ngx/src/lib/interfaces/o-form-layout-manager-mode.interface.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts, projects/ontimize-web-ngx/src/lib/types/form-layout-detail-component-data.type.ts
=> [8.5.7] o-form with after-insert-mode="detail" inside a form layout manager in tab mode bug

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.html, projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.scss
=> Updated o-app-layout-sidenav 

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/app-header/o-app-header.component.html, projects/ontimize-web-ngx/src/lib/components/app-header/o-app-header.component.scss, projects/ontimize-web-ngx/src/lib/layouts/app-layout/app-layout-header/o-app-layout-header.component.ts, projects/ontimize-web-ngx/src/lib/layouts/app-layout/o-app-layout.component.html
=> Added a position attribute for custom elements in o-app-layout-header

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/app-header/o-app-header.component.html, projects/ontimize-web-ngx/src/lib/components/app-header/o-app-header.component.ts, projects/ontimize-web-ngx/src/lib/layouts/app-layout/o-app-layout.component.html, projects/ontimize-web-ngx/src/lib/layouts/app-layout/o-app-layout.component.ts, projects/ontimize-web-ngx/src/lib/services/o-modules-info.service.ts
=> Improvements to set the application title in the toolbar

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/list/list-item/o-list-item.directive.ts, projects/ontimize-web-ngx/src/lib/interfaces/o-list-item.interface.ts
=> Fixed bug in list detail (o-list)

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
=> Fixed error of not keeping selected rows

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.html, projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.ts, projects/ontimize-web-ngx/src/lib/components/input/search-input/o-search-input.component.html, projects/ontimize-web-ngx/src/lib/components/input/search-input/o-search-input.component.scss, projects/ontimize-web-ngx/src/lib/components/input/search-input/o-search-input.component.ts, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.html, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.ts
=> [8.5.8] Modified o-search-input style

projects/ontimize-web-ngx/src/lib/components/app-sidenav/image/o-app-sidenav-image.component.html, projects/ontimize-web-ngx/src/lib/components/button/o-button.component.html, projects/ontimize-web-ngx/src/lib/components/card-menu-item/o-card-menu-item.component.html, projects/ontimize-web-ngx/src/lib/components/image/fullscreen/fullscreen-dialog.component.html, projects/ontimize-web-ngx/src/lib/components/input/date-range/o-daterange-picker.component.html, projects/ontimize-web-ngx/src/lib/components/list/renderers/card-image/o-list-item-card-image.component.html, projects/ontimize-web-ngx/src/lib/components/list/renderers/card/o-list-item-card.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-renderer/boolean/o-table-cell-renderer-boolean.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-renderer/image/o-table-cell-renderer-image.component.html, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.scss, projects/ontimize-web-ngx/src/lib/components/user-info/o-user-info.component.html, projects/ontimize-web-ngx/src/lib/layouts/form-layout/split-pane/o-form-layout-split-pane.component.html, projects/ontimize-web-ngx/src/lib/layouts/form-layout/split-pane/o-form-layout-split-pane.component.scss
Mainly bugs fixed related to:
- `alt` attribute of images
- css duplicated entries
- table `aria-describedby` attribute
=> Fixed reported bugs by Sonar

CHANGELOG.md, projects/ontimize-web-ngx/ontimize.scss, projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.scss, projects/ontimize-web-ngx/src/lib/components/button/o-button.component.scss, projects/ontimize-web-ngx/src/lib/components/form/o-form.component.scss, projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.html, projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.ts, projects/ontimize-web-ngx/src/lib/components/grid/o-grid.theme.scss, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.html, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.scss, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.ts, projects/ontimize-web-ngx/src/lib/components/theming/app-global-theme.scss
- **o-grid**: Fixed that displays 'show more' button when the data length is 0
- Reseted min-height propertie in class **o-mat-menu**
- Setting margin in the buttons inside **o-form-toolbar-buttons**
- Fixed line-height in **stroked button**
- **o-form:** Added the CSS class fill-form 
- **o-grid, o-list:** new attribute show-buttons-text
- **o-app-layout**: Fixed arrow icon position in the menu
=> [8.5.9] Ux changes for theme version 8.2.0

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.scss
=> [8.x.x] o-combo: the height is larger than other input component

CHANGELOG.md, package-lock.json, projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.ts, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.html, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.scss, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.ts, projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/footer/paginator/o-base-table-paginator.class.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/util/codes.ts
Added `mat-paginator` in **o-list** component
The code of the components that inherit from AbstractOServiceComponent was refactored:
- Added `page-size-options` and `pagination-controls` inputs  in DEFAULT_INPUTS_O_SERVICE_COMPONENT array and removed  `page-size-options` and `pagination-controls` in o-table and o-grid
- Added `matpaginator`, `currentPage`, `totalRecords` variables in o-service-component.class.ts and removed in *o-table* component
- Moved  `onChangePage` and `getPaginationDataFromArray` method in o-grid.component.s to o-service-component.class.ts
=> [8.x.x] Pagination for o-list

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/real-input/o-real-input.component.ts
=> [8.6.0] Updating o-real-input and o-percent-input value storage depending on its decimal digits

projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/boolean/o-table-cell-editor-boolean.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/date/o-table-cell-editor-date.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/email/o-table-cell-editor-email.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/integer/o-table-cell-editor-integer.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/o-base-table-cell-editor.class.ts, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/real/o-table-cell-editor-real.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/text/o-table-cell-editor-text.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/time/o-table-cell-editor-time.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/o-column.class.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
=> [8.6.0] Adding new classes to currently editing cell and row

.github/workflows/build-ci.yml, .github/workflows/build-manually.yml, .github/workflows/sonar.yml
It is fixed the installation of correct node version on different Github Actions workflows for version 8.x
=> [8.x.x] Fix installation of correct node version on Github workflows

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/services/navigation.service.ts
=> [8.x.x] The navigation buttons disappear when reloading the page in o-form

projects/ontimize-web-ngx/src/lib/components/bar-menu/menu-group/o-bar-menu-group.component.ts, projects/ontimize-web-ngx/src/lib/components/bar-menu/o-bar-menu.component.ts, projects/ontimize-web-ngx/src/lib/components/material/ckeditor/ck-editor.component.ts, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/o-base-table-cell-editor.class.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts, projects/ontimize-web-ngx/src/lib/util/util.ts
This changes have to be tested
=> [8.x.x] Fix Math.random() for security issues

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
=> [8.x.x] AbstractOServiceBaseComponent 'enabled' input parsing bug

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.ts, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.ts, projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts
=> [8.x.x] Common handlers for click and dblClick

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form.navigation.class.ts, projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts, projects/ontimize-web-ngx/src/lib/components/form/toolbar/o-form-toolbar.component.ts
=> [8.6.1] Multiple discard changes confirmation dialog

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/integer-input/o-integer-input.component.ts, projects/ontimize-web-ngx/src/lib/components/input/listpicker/o-list-picker.component.ts, projects/ontimize-web-ngx/src/lib/components/input/time-input/o-time-input.component.html, projects/ontimize-web-ngx/src/lib/components/o-form-data-component.class.ts, projects/ontimize-web-ngx/src/lib/types/o-inputs-options.type.ts
- New attribute select-all-on-click on OFormDataComponent
- Added new attribute `selectAllOnClick` in O_INPUTS_OPTIONS token
=> [8.6.1] Select text on input focus in inputs

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/integer-input/o-integer-input.component.ts
=> [8.x.x] Fixed bug emit onChange event

projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts, projects/ontimize-web-ngx/src/lib/interfaces/report-on-demand-service.interface.ts, projects/ontimize-web-ngx/src/lib/services/factories.ts
- Renamed O_REPORT_ON_DEMAND_SERVICE by O_REPORT_SERVICE
=> Renamed O_REPORT_ON_DEMAND_SERVICE by O_REPORT_SERVICE 

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/services/state/o-table-component-state.class.ts
=> [8.x.x] Save filter and save configuration first time

CHANGELOG.md, package-lock.json, package.json, projects/ontimize-web-ngx/package.json, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
=> [Hotfix 8.7.1] Pagination does not work in o-table

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/real-input/o-real-input.component.ts
=> [8.x.x] New attribute strict in o-real-input

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
=> o-table: the query is launched to the back when `pageable=no`

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts, projects/ontimize-web-ngx/src/lib/components/input/file-input/o-file-input.component.ts, projects/ontimize-web-ngx/src/lib/components/input/o-form-service-component.class.ts, projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts, projects/ontimize-web-ngx/src/lib/components/table/column/cell-renderer/service/o-table-cell-renderer-service.component.ts, projects/ontimize-web-ngx/src/lib/services/factories.ts, projects/ontimize-web-ngx/src/lib/services/translate/o-translate.service.ts, projects/ontimize-web-ngx/src/lib/types/configure-service-args.type.ts, projects/ontimize-web-ngx/src/lib/util/util.ts
- Fixes #1015
- New OConfigureServiceArgs type
- New configureService(configureServiceArgs: OConfigureServiceArgs) method in utils.ts
- Move createServiceInstance method from factories.ts to utils.ts
=> Bug: multiple components use the same service-type

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/hour-input/o-hour-input.component.ts, projects/ontimize-web-ngx/src/lib/components/o-form-data-component.class.ts
=> [8.x.x] o-hour-input timestamp value storarge bug

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/services/factories.ts
Setting serviceType to OntimizeEE and permissionsServiceType to OntimizeEEPermissions by default
Fixes #967
=> Setting serviceType to OntimizeEE and permissionsServiceType to OntimizeEEPermissions by default

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/search-input/o-search-input.component.scss, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.scss
=> [8.x.x]The arrow button inside the quickfilter prefix is ​​too far apart

projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-header/o-table-header.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
- Fixed sort columns not updating when loading default settings
- Fixed circular dependency
=> fixed sort columns not updating when loading default settings

.github/workflows/build-ci.yml, .github/workflows/build-manually.yml, .github/workflows/build-release.yml, .github/workflows/release-preview.yml, .github/workflows/sonar.yml
=> Fixed NodeJS 12 warning on actions

projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts
=> [8.8.1]Form navigation: clicking on the next or previous button does not navigate between the recordset

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts
=> [8.8.2] multi-column primary keys in form layout manager tab mode bug

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/components/table/styles/o-table-theme.scss
Fixes #1106
Fixed bug in indeterminate checkbox state.
=> New `disable-selection-function` attribute  

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/phone-input/o-phone-input.component.html, projects/ontimize-web-ngx/src/lib/components/input/phone-input/o-phone-input.component.scss
=> Responsible design in o-phone-input

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/container/column-collapsible/o-column-collapsible.component.ts, projects/ontimize-web-ngx/src/lib/components/container/o-container-collapsible-component.class.ts, projects/ontimize-web-ngx/src/lib/components/container/row-collapsible/o-row-collapsible.component.ts
Fixes #1074
New outputs `onClosed, onOpened, onAfterCollapse, onAfterExpand`
=> New outputs `onClosed, onOpened, onAfterCollapse, onAfterExpand`

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/button/o-button.component.ts
=> Border shown on icon buttons set to svg-icon

.github/workflows/build-release.yml, .github/workflows/prepare-release.yml
=> Update workflows involved into release process

projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
=> Hovering over icons reselects item in o-table

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager.component.ts
=> Fixed navigation between transactions fails in production mode 

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/input/file-input/o-file-input.component.ts
=> O-File-Input clear error

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.scss
=> Removed the maximum height limitation in the o-table tooltip

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.html, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.html, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-button/o-table-button.component.ts, projects/ontimize-web-ngx/src/lib/components/theming/app-global-theme.scss
=> Unified button styles

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/image/o-image.component.html, projects/ontimize-web-ngx/src/lib/components/image/o-image.component.scss, projects/ontimize-web-ngx/src/lib/components/image/o-image.component.ts, projects/ontimize-web-ngx/src/lib/components/image/o-image.theme.scss, projects/ontimize-web-ngx/src/lib/components/theming/all-theme.scss, projects/ontimize-web-ngx/src/lib/config/o-directives.ts, projects/ontimize-web-ngx/src/lib/directives/index.ts, projects/ontimize-web-ngx/src/lib/directives/o-file-drag-and-drop.directive.ts, projects/ontimize-web-ngx/src/lib/i18n/i18n.ts, projects/ontimize-web-ngx/src/lib/util/util.ts
- New directive oFileDragAndDrop
- Fixed that it does not load images from a very large url
=> o-image: Add drag&drop functionality

package-lock.json, package.json, projects/ontimize-web-ngx/package.json
Automated pull request for synchronizing released version (8.10.0) into develop branch
=> Sync release 8.10.0 to develop

projects/ontimize-web-ngx/src/lib/components/theming/app-global-theme.scss
primary 500 on dark primary 200 on light
=> Scrollbar color changed on dark mode

projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.html, projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.scss
Fixes #1168 
Remove max-height: 70%; in class name `.navMenu`
Added padding-botton:16px to .mat-drawer-inner-container
=> o-app-layoyt: flexible menu section

projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/visible-columns/o-table-visible-columns-dialog.component.html, projects/ontimize-web-ngx/src/lib/components/theming/app-global-theme.scss
=> Fixed align text right when dragging in window show/hide columns 

projects/ontimize-web-ngx/src/lib/components/input/text-input/o-text-input.component.html, projects/ontimize-web-ngx/src/lib/components/input/text-input/o-text-input.component.ts, projects/ontimize-web-ngx/src/lib/config/o-directives.ts, projects/ontimize-web-ngx/src/lib/directives/index.ts, projects/ontimize-web-ngx/src/lib/directives/o-mat-prefix.directive.ts, projects/ontimize-web-ngx/src/lib/directives/o-mat-suffix.directive.ts
- Allow to add custom content before and after the input tag
- New oMatSuffix and oMatPrefix directives
=> Allow to add custom content before and after the input tag

package-lock.json, package.json, projects/ontimize-web-ngx/package.json
Automated pull request for synchronizing released version (8.11.0) into develop branch
=> Sync release 8.11.0 to develop

projects/ontimize-web-ngx/src/lib/components/o-form-data-component.class.ts
=> o-checkbox: stays disabled if it is initialized with enabled=false

projects/ontimize-web-ngx/src/lib/components/input/o-form-service-component.class.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/o-table.dao.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/util/sqltypes.ts
=> Add UUID support

projects/ontimize-web-ngx/src/lib/components/table/extensions/footer/expanded/o-table-expanded-footer.directive.ts
=> o-table: Do not update the message that there are no results

package-lock.json, package.json, projects/ontimize-web-ngx/package.json
Automated pull request for synchronizing released version (8.12.0) into develop branch
=> Sync release 8.12.0 to develop

projects/ontimize-web-ngx/src/lib/components/input/phone-input/o-phone-input.component.ts
=> o-phone-input countries input bug fix

projects/ontimize-web-ngx/src/lib/services/local-storage.service.ts, projects/ontimize-web-ngx/src/lib/util/util.ts
=> [Bugfix] Filter in table with row grouping

projects/ontimize-web-ngx/src/lib/services/local-storage.service.ts
=> [Bugfix] solved localstorage not saving correctly

package-lock.json, package.json, projects/ontimize-web-ngx/package.json
Automated pull request for synchronizing released version (8.13.0) into develop branch
=> Sync release 8.13.0 to develop

projects/ontimize-web-ngx/src/lib/components/form/guards/o-form-can-deactivate.guard.ts, projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form-confirm-exit.service.ts, projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form.navigation.class.ts, projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts, projects/ontimize-web-ngx/src/lib/interfaces/o-form-layout-manager-mode.interface.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/dialog/o-form-layout-dialog.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/split-pane/o-form-layout-split-pane.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts
=> [Bugfix] o-form canDeactivate and navigation problems

projects/ontimize-web-ngx/src/lib/components/o-form-data-component.class.ts, projects/ontimize-web-ngx/src/lib/shared/components/validation/o-validator.component.ts
=> Adding async-validators to form data components

projects/ontimize-web-ngx/src/lib/components/input/integer-input/o-integer-input.component.ts, projects/ontimize-web-ngx/src/lib/components/o-component.class.ts, projects/ontimize-web-ngx/src/lib/components/o-form-data-component.class.ts, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/date/o-table-cell-editor-date.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/email/o-table-cell-editor-email.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/integer/o-table-cell-editor-integer.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/integer/o-table-cell-editor-integer.component.ts, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/o-base-table-cell-editor.class.ts, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/real/o-table-cell-editor-real.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/real/o-table-cell-editor-real.component.ts, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/text/o-table-cell-editor-text.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/cell-editor/time/o-table-cell-editor-time.component.html, projects/ontimize-web-ngx/src/lib/components/table/column/o-table-column.component.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/o-table-base-dialog.class.ts, projects/ontimize-web-ngx/src/lib/directives/o-mat-error.directive.ts, projects/ontimize-web-ngx/src/lib/interfaces/o-table-column.interface.ts, projects/ontimize-web-ngx/src/lib/util/errors.ts, projects/ontimize-web-ngx/src/lib/validators/o-validators.ts
=> [8.x.x] Add async-validators input to o-table-column 

package-lock.json, package.json, projects/ontimize-web-ngx/package.json
Automated pull request for synchronizing released version (8.14.0) into develop branch
=> Sync release 8.14.0 to develop

.github/workflows/build-release.yml, CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
=> Fixed action columns bug

projects/ontimize-web-ngx/src/lib/components/theming/app-global.theme.scss, projects/ontimize-web-ngx/src/lib/theming/ontimize-style.scss
=> [15.x.x] Font size of o-row, o-column and dialogue titles 

projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.html
=> [o-list, o-grid, o-table] Should not show the placeholder 

projects/ontimize-web-ngx/src/lib/components/o-service-base-component.class.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/util/util.ts
=> [8.14.2]o-table: Bug sorting a column of type translate

projects/ontimize-web-ngx/src/lib/services/o-error-dialog-manager.service.ts
=> [15.x.x] o-error-dialog: fixed bug that prevents opening the dialog

projects/ontimize-web-ngx/src/lib/components/input/input-theme.scss, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-quickfilter/o-table-quickfilter.component.scss, projects/ontimize-web-ngx/src/lib/theming/styles/ontimize-v8/o-form-field-style.scss
=> Fix appearance outline in table quickfilter

projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
=>  o-table: fixed not showing any message that there are no results

projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form.navigation.class.ts
=> Fix(o-form-layout-manager): New detail does not open from the detail

projects/ontimize-web-ngx/src/lib/components/button-toggle/o-button-toggle-group/o-button-toggle-group.component.ts, projects/ontimize-web-ngx/src/lib/components/card-menu-item/o-card-menu-item.component.ts, projects/ontimize-web-ngx/src/lib/components/form-container/o-form-container.component.ts, projects/ontimize-web-ngx/src/lib/components/table/column/calculated/o-table-column-calculated.component.ts, projects/ontimize-web-ngx/src/lib/components/table/column/o-table-column.component.ts, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-insertable-row/o-table-insertable-row.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/interfaces/o-table-column.interface.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/dialog/o-form-layout-dialog.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/split-pane/o-form-layout-split-pane.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.ts
=> [15.x.x] Removed deprecated ComponentFactory

projects/ontimize-web-ngx/src/lib/theming/styles/ontimize-v8/o-form-field-style.scss
1. Fixed height input without label
2. The height of the inputs was also expanded to resemble the inputs of the previous version(36)
=> Fixed height input without label

projects/ontimize-web-ngx/src/lib/theming/ontimize-style.scss
=> Fix mixin ontimize-theme-all-component-color in ontimize-style.scss

projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.scss, projects/ontimize-web-ngx/src/lib/theming/ontimize-style-v8.scss, projects/ontimize-web-ngx/src/lib/theming/styles/ontimize-v8/variables.scss
- Change **default side menu styles to v8** and change **the side menu styles of the old fashion theme to the default**
=> Change default side menu styles to v8

projects/ontimize-web-ngx/src/lib/layouts/form-layout/dialog/o-form-layout-dialog.component.html, projects/ontimize-web-ngx/src/lib/layouts/form-layout/dialog/o-form-layout-dialog.component.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/dialog/options/o-form-layout-dialog-options.directive.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager.component.ts
=> [15.x.x] o-form-layout-manager: New input dialog-title-separator

projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
=> Does not work virtual scroll in o-table 

projects/ontimize-web-ngx/src/lib/components/list/list-item/o-list-item.component.scss, projects/ontimize-web-ngx/src/lib/components/list/renderers/card-image/o-list-item-card-image.component.html, projects/ontimize-web-ngx/src/lib/components/list/renderers/card-image/o-list-item-card-image.component.scss, projects/ontimize-web-ngx/src/lib/components/list/renderers/card/o-list-item-card.component.html, projects/ontimize-web-ngx/src/lib/components/list/renderers/card/o-list-item-card.component.scss
Removed appearance=outline in card and update styles
Fixes #1349
=> o-list: Set padding between card items

projects/ontimize-web-ngx/src/lib/components/app-sidenav/o-app-sidenav.component.scss
=> Collapsed sidenav in Firefox

projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.scss, projects/ontimize-web-ngx/src/lib/theming/styles/ontimize-v8/o-form-field-style.scss
=> Fixes input height  in Firefox

projects/ontimize-web-ngx/src/lib/components/input/phone-input/o-phone-input.component.html
=> o-phone: Fixes height 

projects/ontimize-web-ngx/src/lib/layouts/form-layout/tabgroup/o-form-layout-tabgroup.component.scss
=> [15.x.x] The shape of the close button on the tab is not circular sometimes

projects/ontimize-web-ngx/src/lib/components/list/o-list.component.html, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.scss, projects/ontimize-web-ngx/src/lib/components/list/o-list.component.ts
In Materia v15, the layout dense is removed
=> [o-list] Remove dense input

projects/ontimize-web-ngx/src/lib/theming/addons/report-on-demand.scss
=> [15.x.x] Modified report-on-demand styles

projects/ontimize-web-ngx/src/lib/components/input/file-input/o-file-input.component.ts
=> [15.x.x] Removed the common inputs with OFormDataComponent

projects/ontimize-web-ngx/src/lib/components/input/o-form-service-component.class.ts
=> [15.x.x ]Added change in emitOnValueChange to reset values

projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.html
=> [o-table-menu]Refresh mat-menu descendants

projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.html, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.scss
=> Wrap the o-table button with <span mat-menu-item> so that the submenus collapse when losing focus 

CHANGELOG.md, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.html, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.scss, projects/ontimize-web-ngx/src/lib/components/table/extensions/header/table-menu/o-table-menu.component.ts, projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts, projects/ontimize-web-ngx/src/lib/i18n/i18n.ts, projects/ontimize-web-ngx/src/lib/layouts/form-layout/o-form-layout-manager-base.class.ts
=> Changes from hotfix 8.14.6 to 15.x.x

projects/ontimize-web-ngx/src/lib/components/form/o-form.component.ts
=> [15.x.x] Added new emitters in o-form

projects/ontimize-web-ngx/src/lib/components/input/currency-input/o-currency-input.component.html, projects/ontimize-web-ngx/src/lib/components/input/currency-input/o-currency-input.component.scss, projects/ontimize-web-ngx/src/lib/components/input/currency-input/o-currency-input.component.ts
=> [15.x.x] Modified currency icons

package-lock.json, package.json, projects/ontimize-web-ngx/package.json
Automated pull request for synchronizing released version (15.0.0-beta.4) into develop branch
=> Sync release 15.0.0-beta.4 to develop

package-lock.json, package.json, projects/ontimize-web-ngx/package.json
Automated pull request for synchronizing released version (15.0.0-beta.5) into develop branch
=> Sync release 15.0.0-beta.5 to develop

projects/ontimize-web-ngx/src/lib/services/permissions/o-permissions.module.ts, projects/ontimize-web-ngx/src/lib/services/permissions/permissions.service.ts
=> [15.x.x] Solved bug with permissionsService

package-lock.json, package.json, projects/ontimize-web-ngx/package.json
Automated pull request for synchronizing released version (15.0.0-rc.0) into develop branch
=> Sync release 15.0.0-rc.0 to develop

projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts, projects/ontimize-web-ngx/src/lib/util/util.ts
=> Bug filtering by column in boolean and numeric columns

projects/ontimize-web-ngx/src/lib/components/grid/o-grid.theme.scss
=> Set background to transparent in grid paginator

projects/ontimize-web-ngx/src/lib/components/input/file-input/o-file-input.component.ts
- Added previously removed `service`, `entity` and `service-type` inputs
- Removed unnessary inputs `appearance`, `hide-required-marker`,`label-visible` because they are imported from OformDataComponent
=> Added previously removed `service`, `entity` and `service-type` inputs

projects/ontimize-web-ngx/src/lib/components/grid/o-grid.component.html
=> [15.x.x] [o-grid] Modified insert button translation

projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
=> [8.14.9] [o-table] Added disable-page-size-calculation input in o-table
